const SIGN_IN = "/auth/sign-in";
const SIGN_UP = "/auth/sign-up";
const FORGOT_PASSWORD = "/auth/forgot-password";
const VERIFY_EMAIL = "/auth/verify-email";
const RESET_PASSWORD = "/auth/reset-password";
const CONTINUE_SIGN_UP = "/auth/continue-sign-up";
const PROFILE = '/(tabs)/profile';
const BILLS = '/(tabs)/bills';
const HOME = '/(root)/(tabs)';
const ACCOUNT_PREFERENCE = '/profile/account-preference';
const PRIVACY_POLICY = '/profile/privacy-policy';
const TERMS_OF_SERVICES = '/profile/terms-of-services';
const SUPPORT = '/profile/support';
const ACCOUNT_SECURITY = '/profile/account-security';
const PROFILE_INFORMATION = '/profile/profile-information';
const BUSINESS_PROFILE = '/profile/business-profile';
const MANAGE_SERVICES = '/profile/manage-services';
const EARNINGS = '/profile/earnings';
const CERTIFICATES = '/profile/certificates';

export { SIGN_IN, SIGN_UP, FORGOT_PASSWORD, VERIFY_EMAIL, RESET_PASSWORD, CONTINUE_SIGN_UP, PROFILE, HOME, ACCOUNT_PREFERENCE, PRIVACY_POLICY, TERMS_OF_SERVICES, SUPPORT, ACCOUNT_SECURITY, PROFILE_INFORMATION, BUSINESS_PROFILE, MANAGE_SERVICES, EARNINGS, CERTIFICATES, BILLS };
